
name: PR Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  test_approved_or_docs:
    name: Test approved or docs
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@master
        id: checkLabel
        with:
          hasSome: PR:tested,PR:no testing needed,docs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  merge_blocked:
    name: Merge blocked
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@master
        id: checkLabel
        with:
          hasNone: PR:reviewing
          githubToken: ${{ secrets.GITHUB_TOKEN }}
